added common configuration file

diff --git a/bin/chktid b/bin/chktid
--- a/bin/chktid
+++ b/bin/chktid
@@ -1,13 +1,13 @@
 #!/bin/bash
-SVER='1.0.0'
+SVER='1.0.1'
 
 ##############################################################################
 #  chktid - TID Checker
-#  Copyright (C) 2020 SUSE LLC
+#  Copyright (C) 2020-2021 SUSE LLC
 #
 # Description:  Checks existing patterns for the string given, usually a TID
 #               number.
-# Modified:     2020 Dec 14
+# Modified:     2021 Jan 25
 #
 ##############################################################################
 #
@@ -24,15 +24,17 @@ SVER='1.0.0'
 #  along with this program; if not, see <http://www.gnu.org/licenses/>.
 #
 #  Authors/Contributors:
-#     Jason Record (jason.record@suse.com)
+#     Jason Record <jason.record@suse.com>
 #
 ##############################################################################
 
 
+LCONF='/etc/opt/patdev/patdev.conf'
+[[ -s $LCONF ]] && . $LCONF || { echo "ERROR: File not found, $LCONF"; echo; exit 1; }
+
 clear
 echo "Checking Patterns for $1"
-BASE="/opt/patdev/patterns"
-cd ${BASE}
-find ${BASE}/ -type f | grep patterns | sort | xargs grep "$1"
+cd ${PATDEV_BASE}
+find ${PATDEV_BASE}/ -type f | grep patterns | sort | xargs grep "$1"
 echo
 
diff --git a/bin/gitpatterns b/bin/gitpatterns
--- a/bin/gitpatterns
+++ b/bin/gitpatterns
@@ -1,10 +1,38 @@
 #!/bin/bash
+SVER='1.0.1'
 
-REPO_DIR="/opt/patdev/patterns"
-REPOS="sca-server-report sca-patterns-base sca-patterns-sle11 sca-patterns-sle12 sca-patterns-sle15 sca-patterns-hae sca-patterns-suma"
+##############################################################################
+#  chktid - TID Checker
+#  Copyright (C) 2020-2021 SUSE LLC
+#
+# Description:  Checks existing patterns for the string given, usually a TID
+#               number.
+# Modified:     2021 Jan 25
+#
+##############################################################################
+#
+#  This program is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation; version 2 of the License.
+#
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
+#
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, see <http://www.gnu.org/licenses/>.
+#
+#  Authors/Contributors:
+#     Jason Record <jason.record@suse.com>
+#
+##############################################################################
 
-cd $REPO_DIR
-for i in $REPOS
+LCONF='/etc/opt/patdev/patdev.conf'
+[[ -s $LCONF ]] && . $LCONF || { echo "ERROR: File not found, $LCONF"; echo; exit 1; }
+
+cd $PATDEV_REPO_DIR
+for i in $PATDEV_REPOS
 do
 	if [[ -d $i ]]; then
 		echo "Updating $i Repo..."
diff --git a/bin/gvc b/bin/gvc
--- a/bin/gvc
+++ b/bin/gvc
@@ -1,6 +1,5 @@
 #!/bin/bash
-SVER='1.0.1'
-EMAIL=''
+SVER='1.0.2'
 
 ##############################################################################
 # gvc - GitHub change log and spec file editor
@@ -26,12 +25,15 @@ EMAIL=''
 #  along with this program; if not, see <http://www.gnu.org/licenses/>.
 #
 #  Authors/Contributors:
-#     Jason Record (jason.record@suse.com)
+#     Jason Record <jason.record@suse.com>
 #
 ##############################################################################
 
-if [[ -z $EMAIL ]]; then
-	echo "ERROR: Missing EMAIL variable. Edit this script and add your"
+LCONF='/etc/opt/patdev/patdev.conf'
+[[ -s $LCONF ]] && . $LCONF || { echo "ERROR: File not found, $LCONF"; echo; exit 1; }
+
+if [[ -z $PATDEV_EMAIL ]]; then
+	echo "ERROR: Empty PATDEV_EMAIL variable. Edit $LCONF to add your"
 	echo "       valid email address."
 	exit 1
 fi
@@ -55,7 +57,7 @@ else
 	if [[ -s $CHANGELOG ]]
 	then
 		echo '-------------------------------------------------------------------' > $TMP_CHANGELOG
-		echo "$(date -u) - $EMAIL" >> $TMP_CHANGELOG
+		echo "$(date -u) - $PATDEV_EMAIL" >> $TMP_CHANGELOG
 		echo >> $TMP_CHANGELOG
 		echo "- " >> $TMP_CHANGELOG
 		echo >> $TMP_CHANGELOG
diff --git a/bin/pat b/bin/pat
--- a/bin/pat
+++ b/bin/pat
@@ -1,12 +1,12 @@
 #!/bin/bash
-SVER='1.0.11'
+SVER='1.0.12'
 
 ##############################################################################
 #  pat - Pattern Tester Tool
-#  Copyright (C) 2014-2020 SUSE LLC
+#  Copyright (C) 2014-2021 SUSE LLC
 #
 # Description:  Tests one pattern against several supportconfig archives.
-# Modified:     2020 Dec 14
+# Modified:     2021 Jan 25
 #
 ##############################################################################
 #
@@ -23,9 +23,12 @@ SVER='1.0.11'
 #  along with this program; if not, see <http://www.gnu.org/licenses/>.
 #
 #  Authors/Contributors:
-#     Jason Record (jason.record@suse.com)
+#     Jason Record <jason.record@suse.com>
 #
 ##############################################################################
+
+LCONF='/etc/opt/patdev/patdev.conf'
+[[ -s $LCONF ]] && . $LCONF || { echo "ERROR: File not found, $LCONF"; echo; exit 1; }
 
 : ${SCA_LIBRARY_PATH:="/opt/patdev/patterns/sca-patterns-base/libraries"}
 : ${SCA_PATTERN_PATH:="/opt/patdev/patterns"}
@@ -161,7 +164,8 @@ if head -1 $PATFULL | grep '^ ' &>/dev/null; then
 	((ERR_HPL++))
 fi
 [[ ! -x $PATFULL ]] && { ((ERR_MODE++)); ((RET_FAT++)); }
-if grep  $PATFULL &>/dev/null
+if grep 
+ $PATFULL &>/dev/null
 then
 	((RET_FAT++))
 	((ERR_DOS++))
